namespace RagNet.Mcp.Configuration;

public sealed class RagNetOptions
{
    public const string SectionName = "RagNet";

    public OllamaOptions Ollama { get; init; } = new();

    public QdrantOptions Qdrant { get; init; } = new();

    public WorkspaceOptions Workspace { get; init; } = new();

    public IReadOnlyList<WorkspaceGroupOptions> WorkspaceGroups { get; init; } = [];

    public IndexingOptions Indexing { get; init; } = new();

    public ClassificationOptions Classification { get; init; } = new();
}

public sealed class OllamaOptions
{
    public string BaseUrl { get; init; } = "http://localhost:11434";

    public string EmbeddingModel { get; init; } = "mxbai-embed-large";
}

public sealed class QdrantOptions
{
    public string BaseUrl { get; init; } = "http://localhost:6333";

    public string CollectionPrefix { get; init; } = "ragnet";

    public int UpsertBatchSize { get; init; } = 256;
}

public sealed class WorkspaceOptions
{
    public bool AutoIndex { get; init; } = false;

    public IReadOnlyList<string> AllowedPaths { get; init; } = [];

    public IReadOnlyList<string> ExcludeDirectories { get; init; } =
    [
        ".git",
        ".ragnet",
        ".vs",
        ".vscode",
        "bin",
        "obj",
        "node_modules",
        "packages"
    ];

    public IReadOnlyList<string> ExcludeFilePatterns { get; init; } =
    [
        "*.g.cs",
        "*.Designer.cs"
    ];

    public bool ExcludeAutoGeneratedFiles { get; init; } = true;
}

public sealed class WorkspaceGroupOptions
{
    public string Name { get; init; } = string.Empty;

    public IReadOnlyList<string> Roots { get; init; } = [];

    public IReadOnlyList<string> ExcludeDirectories { get; init; } = [];
}

public sealed class IndexingOptions
{
    public int ChunkMaxChars { get; init; } = 30_000;

    public int MaxEmbeddingConcurrency { get; init; } = 4;

    public int MaxEmbeddingBatchSize { get; init; } = 16;
}

public sealed class ClassificationOptions
{
    public IReadOnlyList<string> DocumentationPathPatterns { get; init; } =
    [
        "**/doc/**",
        "**/docs/**",
        "**/documentation/**",
        "**/api-docs/**",
        "**/generated-docs/**"
    ];

    public IReadOnlyList<string> ApplicationMarkupPathPatterns { get; init; } =
    [
        "**/src/**",
        "**/app/**",
        "**/apps/**",
        "**/client/**",
        "**/frontend/**",
        "**/ui/**",
        "**/views/**",
        "**/pages/**",
        "**/components/**",
        "**/wwwroot/**"
    ];
}
